'use client';

/**
 * Presentation Generator Skill Renderer.
 *
 * Slideshow UI that renders Markdown slides generated by the AI coach.
 * Parses <slides>...</slides> from coach responses and renders them
 * as an interactive slide deck with navigation controls.
 *
 * Phases: generating → viewing
 * Supports <slides>Markdown</slides> parsing from coach responses.
 */

import { useState, useRef, useCallback, useEffect, useMemo } from 'react';
import dynamic from 'next/dynamic';
import ChatInputArea from '@/components/ChatInputArea';
import type { SkillRendererProps } from '@/lib/plugin/types';
import styles from './PresentationRenderer.module.css';
import RevealDeck from '@/components/RevealDeck';
import { useTelemetry } from '@/lib/useTelemetry';
import TextSelectionTooltip from '@/components/TextSelectionTooltip';

const MarkdownRenderer = dynamic(() => import('@/components/MarkdownRenderer'));

// -- Types -------------------------------------------------------

interface ChatMessage {
    id: string;
    role: 'student' | 'coach' | 'system';
    content: string;
    timestamp: number;
}

type PresentationPhase = 'generating' | 'viewing' | 'idle';

// -- Slides Parser -----------------------------------------------

/**
 * Extracts markdown slides content from coach response.
 * Supports two formats:
 * 1. Wrapped in <slides> tags
 * 2. Direct Reveal.js markdown (contains --- separators)
 *
 * @param content - Raw coach response string
 * @returns Slide markdown string, or null if no slides found
 */
function parseSlidesFromContent(content: string): string | null {
    // Try format 1: <slides> tag
    const tagMatch = content.match(/<slides>([\s\S]*?)<\/slides>/);
    if (tagMatch) {
        let slides = tagMatch[1].trim();
        slides = slides.replace(/<reasoning>[\s\S]*?<\/reasoning>/g, '');
        slides = slides.replace(/<thinking>[\s\S]*?<\/thinking>/g, '');
        slides = slides.replace(/<analysis>[\s\S]*?<\/analysis>/g, '');
        return slides.trim();
    }
    
    // Try format 2: Direct Reveal.js markdown (has --- separators and typical slide structure)
    if (content.includes('---') && (content.includes('##') || content.includes('#'))) {
        console.log('[PresentationRenderer] Detected direct Reveal.js format');
        return content.trim();
    }
    
    return null;
}

/**
 * Strips the <slides> tag and slide content from a message, returning any surrounding text.
 *
 * @param content - Raw coach response string
 * @returns The content with the slides and reasoning blocks removed
 */
function stripSlidesTag(content: string): string {
    let result = content;
    
    // Remove <slides> tag content
    result = result.replace(/<slides>[\s\S]*?<\/slides>/, '');
    
    // If no <slides> tag but has Reveal.js format, remove it
    if (content.includes('---') && (content.includes('##') || content.includes('#'))) {
        // This is likely a direct Reveal.js format, remove all of it
        result = '';
    }
    
    // Remove reasoning tags
    result = result.replace(/<reasoning>[\s\S]*?<\/reasoning>/g, '');
    result = result.replace(/<thinking>[\s\S]*?<\/thinking>/g, '');
    result = result.replace(/<analysis>[\s\S]*?<\/analysis>/g, '');
    
    return result.trim();
}



// -- Component ---------------------------------------------------

export default function PresentationRenderer({
    agentChannel,
    onInteractionEvent,
    initialMessages = [],
    studentContext,
    knowledgePoint,
}: SkillRendererProps) {
    const [messages, setMessages] = useState<ChatMessage[]>([]);
    const [input, setInput] = useState('');
    const [sending, setSending] = useState(false);
    const [thinkingStatus, setThinkingStatus] = useState<string | null>(null);
    const streamingContentRef = useRef('');
    const [streamingContent, setStreamingContent] = useState('');

    const { trackEvent } = useTelemetry(studentContext?.sessionId || 0, studentContext?.courseId || 0);

    const handleSlideChange = useCallback((indexh: number, indexv: number) => {
        trackEvent({
            event_type: 'custom',
            skill_id: 'presentation_generator',
            kp_id: knowledgePoint?.id,
            trigger_reason: 'slide_changed',
            metadata: {
                slide_h: indexh,
                slide_v: indexv,
                timestamp: Date.now()
            }
        });
    }, [trackEvent, knowledgePoint]);

    // Presentation-specific state
    const [phase, setPhase] = useState<PresentationPhase>('generating');
    const [slidesMarkdown, setSlidesMarkdown] = useState<string | null>(null);
    const [isFullscreen, setIsFullscreen] = useState(false);

    const messagesEndRef = useRef<HTMLDivElement>(null);
    const slideContainerRef = useRef<HTMLDivElement>(null);
    const hasTriggeredRef = useRef(false);

    // -- Load initial messages -----------------------------------

    useEffect(() => {
        if (!initialMessages || initialMessages.length === 0) return;
        
        const parsedMessages: ChatMessage[] = [];
        let foundSlides: string | null = null;
        
        for (const msg of initialMessages) {
            if (msg.role === 'coach' && msg.content) {
                const s = parseSlidesFromContent(msg.content);
                if (s) {
                    foundSlides = s;
                    const intro = stripSlidesTag(msg.content);
                    if (intro) {
                        parsedMessages.push({
                            id: msg.id || `coach-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
                            role: 'coach',
                            content: intro,
                            timestamp: msg.timestamp || Date.now(),
                        });
                    }
                } else {
                    parsedMessages.push({
                        id: msg.id || `msg-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
                        role: msg.role as 'student' | 'coach' | 'system',
                        content: msg.content,
                        timestamp: msg.timestamp || Date.now(),
                    });
                }
            } else {
                parsedMessages.push({
                    id: msg.id || `msg-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
                    role: msg.role as 'student' | 'coach' | 'system',
                    content: msg.content,
                    timestamp: msg.timestamp || Date.now(),
                });
            }
        }
        
        setTimeout(() => {
            setMessages(parsedMessages);
            if (foundSlides) {
                setSlidesMarkdown(foundSlides);
                setPhase('idle');
                hasTriggeredRef.current = true;
            }
        }, 0);
    }, [initialMessages]);

    // -- Auto-generate if no initial messages --------------------

    useEffect(() => {
        if (
            !hasTriggeredRef.current &&
            initialMessages.length === 0 &&
            messages.length === 0 &&
            !sending &&
            !streamingContent
        ) {
            hasTriggeredRef.current = true;
            setTimeout(() => {
                setSending(true);
                setPhase('generating');
            }, 0);
            
            // Auto-trigger the backend to start generating the presentation
            agentChannel.send(JSON.stringify({
                event: 'user_message',
                payload: { text: '你好，请根据当前知识点生成一份详细的演示文稿。' },
                timestamp: Math.floor(Date.now() / 1000),
            }));
        }
    }, [initialMessages.length, messages.length, sending, streamingContent, agentChannel]);

    // -- Scroll to bottom ----------------------------------------

    const scrollToBottom = useCallback(() => {
        messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    }, []);

    useEffect(() => {
        scrollToBottom();
    }, [messages, streamingContent, thinkingStatus, scrollToBottom]);

    // -- ESC key to exit fullscreen ------------------------------

    useEffect(() => {
        const handleKeyDown = (e: KeyboardEvent) => {
            if (e.key === 'Escape' && isFullscreen) {
                setIsFullscreen(false);
            }
        };

        window.addEventListener('keydown', handleKeyDown);
        return () => window.removeEventListener('keydown', handleKeyDown);
    }, [isFullscreen]);

    // -- Keyboard navigation ------------------------------------

    useEffect(() => {
        if (phase !== 'viewing') return;

        const handleKeyDown = (e: KeyboardEvent) => {
            if (e.key === 'Escape' && isFullscreen) {
                setIsFullscreen(false);
            } else if (e.key === 'f' || e.key === 'F') {
                setIsFullscreen(prev => !prev);
            }
        };

        window.addEventListener('keydown', handleKeyDown);
        return () => window.removeEventListener('keydown', handleKeyDown);
    }, [phase, isFullscreen]);

    // -- WebSocket message handling ------------------------------

    useEffect(() => {
        const unsubscribeMessage = agentChannel.onMessage((data: string) => {
            try {
                const event = JSON.parse(data);
                switch (event.event) {
                    case 'agent_thinking': {
                        setThinkingStatus(event.payload?.status || '正在生成演示文稿...');
                        break;
                    }
                    case 'token_delta': {
                        setThinkingStatus(null);
                        const newText = event.payload?.text || '';
                        streamingContentRef.current += newText;
                        // 不显示流式内容，只累积
                        // setStreamingContent(streamingContentRef.current);
                        break;
                    }
                    case 'turn_complete': {
                        setThinkingStatus(null);
                        setSending(false);
                        const prev = streamingContentRef.current;
                        if (prev) {
                            console.log('[PresentationRenderer] turn_complete, content length:', prev.length);
                            console.log('[PresentationRenderer] checking for <slides> tag...');
                            
                            const parsed = parseSlidesFromContent(prev);
                            if (parsed) {
                                console.log('[PresentationRenderer] ✅ Found slides, length:', parsed.length);
                                // 找到了 slides 标签
                                setSlidesMarkdown(parsed);
                                setPhase('idle');

                                // 只添加 slides 外的介绍文字（如果有）
                                const intro = stripSlidesTag(prev);
                                if (intro) {
                                    console.log('[PresentationRenderer] Adding intro message, length:', intro.length);
                                    setMessages(msgs => [...msgs, {
                                        id: `coach-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
                                        role: 'coach',
                                        content: intro,
                                        timestamp: Date.now(),
                                    }]);
                                }

                                onInteractionEvent({
                                    type: 'presentation_generated',
                                    payload: {
                                        skillId: 'presentation_generator',
                                    },
                                    timestamp: Date.now(),
                                });
                            } else {
                                console.log('[PresentationRenderer] ❌ No slides found, adding as regular message');
                                // 没有 slides 标签，添加完整内容作为普通消息
                                setMessages(msgs => [...msgs, {
                                    id: `coach-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
                                    role: 'coach',
                                    content: prev,
                                    timestamp: Date.now(),
                                }]);
                            }
                        }
                        // 清空流式内容
                        streamingContentRef.current = '';
                        setStreamingContent('');
                        break;
                    }
                    case 'ui_scaffold_change': {
                        const payload = event.payload as {
                            data: { new_level: string; mastery: number; direction: string };
                        };
                        const direction = payload.data.direction === 'fade' ? '降低' : '增强';
                        const labels = { high: '高支架', medium: '中支架', low: '低支架' };
                        const label = labels[payload.data.new_level as keyof typeof labels] || payload.data.new_level;
                        setMessages(prev => [...prev, {
                            id: `sys-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
                            role: 'system',
                            content: `支架已${direction}至 ${label} (掌握度: ${(payload.data.mastery * 100).toFixed(0)}%)`,
                            timestamp: Date.now(),
                        }]);
                        break;
                    }
                    case 'error': {
                        setThinkingStatus(null);
                        setSending(false);
                        setMessages(prev => [...prev, {
                            id: `err-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
                            role: 'system',
                            content: event.payload?.message || '发生错误',
                            timestamp: Date.now(),
                        }]);
                        break;
                    }
                }
            } catch {
                // Ignore parse errors
            }
        });

        const unsubscribeClose = agentChannel.onClose(() => {
            setMessages(prev => [...prev, {
                id: `sys-close-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
                role: 'system',
                content: '连接已断开',
                timestamp: Date.now(),
            }]);
        });
        return () => {
            unsubscribeMessage();
            unsubscribeClose();
        };
    }, [agentChannel, onInteractionEvent]);

    // -- Request regeneration ------------------------------------

    const handleRegenerate = useCallback(() => {
        setPhase('generating');
        setSlidesMarkdown(null);

        agentChannel.send(JSON.stringify({
            event: 'user_message',
            payload: { text: '请重新生成演示文稿' },
            timestamp: Math.floor(Date.now() / 1000),
        }));

        setSending(true);
        streamingContentRef.current = '';
        setStreamingContent('');
    }, [agentChannel]);

    // -- Free-form message send ---------------------------------

    const handleSend = useCallback(() => {
        const text = input.trim();
        if (!text || sending) return;

        setMessages(prev => [...prev, {
            id: `student-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
            role: 'student',
            content: text,
            timestamp: Date.now(),
        }]);

        agentChannel.send(JSON.stringify({
            event: 'user_message',
            payload: { text },
            timestamp: Math.floor(Date.now() / 1000),
        }));

        setInput('');
        setSending(true);
        streamingContentRef.current = '';
        setStreamingContent('');
    }, [input, sending, agentChannel]);

    

    // -- Render Slide Viewer or Content wrapper -----------------

    const handleAskAI = useCallback((selectedText: string) => {
        setInput(prev => {
            const prefix = prev.length > 0 && !prev.endsWith('\n') ? prev + '\n' : prev;
            return prefix + `> ${selectedText}\n\n请解释一下这段话：`;
        });
        // Optionally focus the input if possible, but state update might be enough
    }, []);

    const renderThinking = () => {
        if (!thinkingStatus) return null;
        return (
            <div className={styles.thinkingIndicator}>
                <div className={styles.thinkingDots}>
                    <div className={styles.thinkingDot} />
                    <div className={styles.thinkingDot} />
                    <div className={styles.thinkingDot} />
                </div>
                <span>{thinkingStatus}</span>
            </div>
        );
    };

    // -- Render slide viewer -------------------------------------

    const renderSlideViewer = () => {
        if (!slidesMarkdown) return null;

        return (
            <div
                ref={slideContainerRef}
                className={`${styles.slideViewer} ${isFullscreen ? styles.slideViewerFullscreen : ''}`}
            >
                {/* Toolbar */}
                <div className={styles.slideToolbar}>
                    <div className={styles.slideCounter}>
                        <span className={styles.slideCounterCurrent}>📊 演示文稿</span>
                    </div>
                    <div className={styles.toolbarActions}>
                        {!isFullscreen ? (
                            <>
                                <button
                                    className={styles.toolbarBtn}
                                    onClick={() => setIsFullscreen(true)}
                                    title="全屏模式 (F)"
                                >
                                    ⛶ 全屏
                                </button>
                                <button
                                    className={styles.toolbarBtn}
                                    onClick={handleRegenerate}
                                    disabled={sending}
                                    title="重新生成"
                                >
                                    🔄 重新生成
                                </button>
                            </>
                        ) : (
                            <button
                                className={styles.toolbarBtn}
                                onClick={() => setIsFullscreen(false)}
                                title="退出全屏 (ESC)"
                            >
                                ✕ 退出全屏
                            </button>
                        )}
                    </div>
                </div>

                {/* RevealDeck with fullscreen support */}
                <div className={styles.slideContent}>
                    <RevealDeck 
                        key={slidesMarkdown} 
                        markdown={slidesMarkdown} 
                        onSlideChange={handleSlideChange}
                        fullscreen={isFullscreen}
                    />
                </div>

                {/* Fullscreen exit hint */}
                {isFullscreen && (
                    <div className={styles.fullscreenHint}>
                        按 <kbd>ESC</kbd> 或 <kbd>F</kbd> 退出全屏
                    </div>
                )}
            </div>
        );
    };

    // -- Main render ---------------------------------------------

    return (
        <div className={styles.presentationContainer}>
            <TextSelectionTooltip onAsk={handleAskAI} />
            {/* Messages area */}
            <div className={styles.messagesArea}>
                {messages.map(msg => (
                    <div
                        key={msg.id}
                        className={`${styles.messageBubble} ${msg.role === 'student' ? styles.messageStudent :
                                msg.role === 'coach' ? styles.messageCoach :
                                    styles.messageSystem
                            }`}
                    >
                        {msg.role !== 'system' && (
                            <div className={styles.messageHeader}>
                                <span className={`${styles.roleIcon} ${msg.role === 'student' ? styles.roleStudent : styles.roleCoach
                                    }`}>
                                    {msg.role === 'student' ? 'S' : 'AI'}
                                </span>
                                <span className={styles.roleLabel}>
                                    {msg.role === 'student' ? '我' : 'AI 导师'}
                                </span>
                            </div>
                        )}
                        <div className={styles.messageContent}>
                            {msg.role === 'coach' ? (
                                <MarkdownRenderer content={stripSlidesTag(msg.content)} />
                            ) : (
                                msg.content
                            )}
                        </div>
                    </div>
                ))}

                {renderThinking()}

                {/* Embedded Slide Viewer - Always show when slides are available */}
                {slidesMarkdown && renderSlideViewer()}

                <div ref={messagesEndRef} />
            </div>

            {/* Input */}
            <ChatInputArea
                input={input}
                setInput={setInput}
                sending={sending}
                onSend={() => handleSend()}
                placeholder={sending ? '处理中...' : '输入消息...'}
            />
        </div>
    );
}