'use client';

/**
 * Presentation Generator Skill Renderer.
 *
 * Slideshow UI that renders Markdown slides generated by the AI coach.
 * Parses <slides>...</slides> from coach responses and renders them
 * as an interactive slide deck with navigation controls.
 *
 * Phases: generating → viewing
 * Supports <slides>Markdown</slides> parsing from coach responses.
 */

import { useState, useRef, useCallback, useEffect, useMemo } from 'react';
import dynamic from 'next/dynamic';
import type { SkillRendererProps } from '@/lib/plugin/types';
import styles from './PresentationRenderer.module.css';

const MarkdownRenderer = dynamic(() => import('@/components/MarkdownRenderer'));

// -- Types -------------------------------------------------------

interface ChatMessage {
    id: string;
    role: 'student' | 'coach' | 'system';
    content: string;
    timestamp: number;
}

type PresentationPhase = 'generating' | 'viewing';

// -- Slides Parser -----------------------------------------------

/**
 * Extracts markdown slides content from the <slides> tag.
 *
 * @param content - Raw coach response string
 * @returns Array of slide markdown strings, or null if no slides found
 */
function parseSlidesFromContent(content: string): string[] | null {
    const match = content.match(/<slides>([\s\S]*?)<\/slides>/);
    if (!match) return null;
    const raw = match[1].trim();
    // Split by horizontal rule separator (---)
    const slides = raw.split(/\n---\n/).map(s => s.trim()).filter(Boolean);
    return slides.length > 0 ? slides : null;
}

/**
 * Strips the <slides> tag from a message, returning any surrounding text.
 *
 * @param content - Raw coach response string
 * @returns The content with the <slides> block removed
 */
function stripSlidesTag(content: string): string {
    return content.replace(/<slides>[\s\S]*?<\/slides>/, '').trim();
}

/**
 * Extracts speaker notes from a slide's markdown.
 * Notes are formatted as blockquote lines starting with "备注：".
 *
 * @param slideMarkdown - Single slide's markdown content
 * @returns Object with slide content and speaker notes separated
 */
function extractSpeakerNotes(slideMarkdown: string): { content: string; notes: string | null } {
    const lines = slideMarkdown.split('\n');
    const contentLines: string[] = [];
    const noteLines: string[] = [];
    let inNotes = false;

    for (const line of lines) {
        if (line.match(/^>\s*备注[：:]/)) {
            inNotes = true;
            noteLines.push(line.replace(/^>\s*备注[：:]\s*/, '').trim());
        } else if (inNotes && line.startsWith('>')) {
            noteLines.push(line.replace(/^>\s*/, '').trim());
        } else {
            inNotes = false;
            contentLines.push(line);
        }
    }

    return {
        content: contentLines.join('\n').trim(),
        notes: noteLines.length > 0 ? noteLines.join('\n') : null,
    };
}

// -- Component ---------------------------------------------------

export default function PresentationRenderer({
    agentChannel,
    onInteractionEvent,
}: SkillRendererProps) {
    const [messages, setMessages] = useState<ChatMessage[]>([]);
    const [input, setInput] = useState('');
    const [sending, setSending] = useState(false);
    const [thinkingStatus, setThinkingStatus] = useState<string | null>(null);
    const [streamingContent, setStreamingContent] = useState('');

    // Presentation-specific state
    const [phase, setPhase] = useState<PresentationPhase>('generating');
    const [slides, setSlides] = useState<string[]>([]);
    const [currentSlide, setCurrentSlide] = useState(0);
    const [showNotes, setShowNotes] = useState(false);
    const [isFullscreen, setIsFullscreen] = useState(false);

    const messagesEndRef = useRef<HTMLDivElement>(null);
    const inputRef = useRef<HTMLTextAreaElement>(null);
    const slideContainerRef = useRef<HTMLDivElement>(null);

    // -- Parse current slide content & notes ---------------------

    const currentSlideData = useMemo(() => {
        if (slides.length === 0 || currentSlide >= slides.length) {
            return { content: '', notes: null };
        }
        return extractSpeakerNotes(slides[currentSlide]);
    }, [slides, currentSlide]);

    // -- Scroll to bottom ----------------------------------------

    const scrollToBottom = useCallback(() => {
        messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    }, []);

    useEffect(() => {
        scrollToBottom();
    }, [messages, streamingContent, thinkingStatus, scrollToBottom]);

    // -- Keyboard navigation ------------------------------------

    useEffect(() => {
        if (phase !== 'viewing') return;

        const handleKeyDown = (e: KeyboardEvent) => {
            if (e.key === 'ArrowRight' || e.key === 'ArrowDown' || e.key === ' ') {
                e.preventDefault();
                setCurrentSlide(prev => Math.min(prev + 1, slides.length - 1));
            } else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
                e.preventDefault();
                setCurrentSlide(prev => Math.max(prev - 1, 0));
            } else if (e.key === 'Home') {
                e.preventDefault();
                setCurrentSlide(0);
            } else if (e.key === 'End') {
                e.preventDefault();
                setCurrentSlide(slides.length - 1);
            } else if (e.key === 'Escape' && isFullscreen) {
                setIsFullscreen(false);
            } else if (e.key === 'f' || e.key === 'F') {
                setIsFullscreen(prev => !prev);
            } else if (e.key === 'n' || e.key === 'N') {
                setShowNotes(prev => !prev);
            }
        };

        window.addEventListener('keydown', handleKeyDown);
        return () => window.removeEventListener('keydown', handleKeyDown);
    }, [phase, slides.length, isFullscreen]);

    // -- WebSocket message handling ------------------------------

    useEffect(() => {
        const unsubscribeMessage = agentChannel.onMessage((data: string) => {
            try {
                const event = JSON.parse(data);
                switch (event.event) {
                    case 'agent_thinking': {
                        setThinkingStatus(event.payload?.status || '正在生成演示文稿...');
                        break;
                    }
                    case 'token_delta': {
                        setThinkingStatus(null);
                        setStreamingContent(prev => prev + (event.payload?.text || ''));
                        break;
                    }
                    case 'turn_complete': {
                        setThinkingStatus(null);
                        setSending(false);
                        setStreamingContent(prev => {
                            if (prev) {
                                const parsed = parseSlidesFromContent(prev);
                                if (parsed && parsed.length > 0) {
                                    setSlides(parsed);
                                    setCurrentSlide(0);
                                    setPhase('viewing');

                                    const intro = stripSlidesTag(prev);
                                    if (intro) {
                                        setMessages(msgs => [...msgs, {
                                            id: `coach-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
                                            role: 'coach',
                                            content: intro,
                                            timestamp: Date.now(),
                                        }]);
                                    }

                                    onInteractionEvent({
                                        type: 'presentation_generated',
                                        payload: {
                                            skillId: 'presentation_generator',
                                            slideCount: parsed.length,
                                        },
                                        timestamp: Date.now(),
                                    });
                                } else {
                                    setMessages(msgs => [...msgs, {
                                        id: `coach-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
                                        role: 'coach',
                                        content: prev,
                                        timestamp: Date.now(),
                                    }]);
                                }
                            }
                            return '';
                        });
                        inputRef.current?.focus();
                        break;
                    }
                    case 'ui_scaffold_change': {
                        const payload = event.payload as {
                            data: { new_level: string; mastery: number; direction: string };
                        };
                        const direction = payload.data.direction === 'fade' ? '降低' : '增强';
                        const labels = { high: '高支架', medium: '中支架', low: '低支架' };
                        const label = labels[payload.data.new_level as keyof typeof labels] || payload.data.new_level;
                        setMessages(prev => [...prev, {
                            id: `sys-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
                            role: 'system',
                            content: `支架已${direction}至 ${label} (掌握度: ${(payload.data.mastery * 100).toFixed(0)}%)`,
                            timestamp: Date.now(),
                        }]);
                        break;
                    }
                    case 'error': {
                        setThinkingStatus(null);
                        setSending(false);
                        setMessages(prev => [...prev, {
                            id: `err-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
                            role: 'system',
                            content: event.payload?.message || '发生错误',
                            timestamp: Date.now(),
                        }]);
                        break;
                    }
                }
            } catch {
                // Ignore parse errors
            }
        });

        const unsubscribeClose = agentChannel.onClose(() => {
            setMessages(prev => [...prev, {
                id: `sys-close-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
                role: 'system',
                content: '连接已断开',
                timestamp: Date.now(),
            }]);
        });
        return () => {
            unsubscribeMessage();
            unsubscribeClose();
        };
    }, [agentChannel, onInteractionEvent]);

    // -- Slide navigation ----------------------------------------

    const goToSlide = useCallback((index: number) => {
        setCurrentSlide(Math.max(0, Math.min(index, slides.length - 1)));
    }, [slides.length]);

    const goToPrev = useCallback(() => {
        setCurrentSlide(prev => Math.max(prev - 1, 0));
    }, []);

    const goToNext = useCallback(() => {
        setCurrentSlide(prev => Math.min(prev + 1, slides.length - 1));
    }, [slides.length]);

    // -- Request regeneration ------------------------------------

    const handleRegenerate = useCallback(() => {
        setPhase('generating');
        setSlides([]);
        setCurrentSlide(0);

        agentChannel.send(JSON.stringify({
            event: 'user_message',
            payload: { text: '请重新生成演示文稿' },
            timestamp: Math.floor(Date.now() / 1000),
        }));

        setSending(true);
        setStreamingContent('');
    }, [agentChannel]);

    // -- Free-form message send ---------------------------------

    const handleSend = useCallback(() => {
        const text = input.trim();
        if (!text || sending) return;

        setMessages(prev => [...prev, {
            id: `student-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
            role: 'student',
            content: text,
            timestamp: Date.now(),
        }]);

        agentChannel.send(JSON.stringify({
            event: 'user_message',
            payload: { text },
            timestamp: Math.floor(Date.now() / 1000),
        }));

        setInput('');
        setSending(true);
        setStreamingContent('');

        if (inputRef.current) {
            inputRef.current.style.height = 'auto';
        }
    }, [input, sending, agentChannel]);

    const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
        if (e.key === 'Enter' && !e.shiftKey) {
            e.preventDefault();
            handleSend();
        }
    };

    const handleInputChange = useCallback((e: React.ChangeEvent<HTMLTextAreaElement>) => {
        setInput(e.target.value);
        const textarea = e.target;
        textarea.style.height = 'auto';
        textarea.style.height = Math.min(textarea.scrollHeight, 120) + 'px';
    }, []);

    // -- Render thinking indicator --------------------------------

    const renderThinking = () => {
        if (!thinkingStatus) return null;
        return (
            <div className={styles.thinkingIndicator}>
                <div className={styles.thinkingDots}>
                    <div className={styles.thinkingDot} />
                    <div className={styles.thinkingDot} />
                    <div className={styles.thinkingDot} />
                </div>
                <span>{thinkingStatus}</span>
            </div>
        );
    };

    // -- Render slide viewer -------------------------------------

    const renderSlideViewer = () => {
        if (slides.length === 0) return null;

        return (
            <div
                ref={slideContainerRef}
                className={`${styles.slideViewer} ${isFullscreen ? styles.slideViewerFullscreen : ''}`}
            >
                {/* Toolbar */}
                <div className={styles.slideToolbar}>
                    <div className={styles.slideCounter}>
                        <span className={styles.slideCounterCurrent}>{currentSlide + 1}</span>
                        <span className={styles.slideCounterSep}>/</span>
                        <span className={styles.slideCounterTotal}>{slides.length}</span>
                    </div>
                    <div className={styles.toolbarActions}>
                        <button
                            className={`${styles.toolbarBtn} ${showNotes ? styles.toolbarBtnActive : ''}`}
                            onClick={() => setShowNotes(prev => !prev)}
                            title="演讲备注 (N)"
                        >
                            📝
                        </button>
                        <button
                            className={styles.toolbarBtn}
                            onClick={() => setIsFullscreen(prev => !prev)}
                            title="全屏模式 (F)"
                        >
                            {isFullscreen ? '⬜' : '⛶'}
                        </button>
                        <button
                            className={styles.toolbarBtn}
                            onClick={handleRegenerate}
                            disabled={sending}
                            title="重新生成"
                        >
                            🔄
                        </button>
                    </div>
                </div>

                {/* Slide content */}
                <div className={styles.slideContent}>
                    <MarkdownRenderer content={currentSlideData.content} />
                </div>

                {/* Speaker notes */}
                {showNotes && currentSlideData.notes && (
                    <div className={styles.speakerNotes}>
                        <div className={styles.speakerNotesLabel}>📌 演讲备注</div>
                        <div className={styles.speakerNotesContent}>
                            {currentSlideData.notes}
                        </div>
                    </div>
                )}

                {/* Navigation */}
                <div className={styles.slideNavigation}>
                    <button
                        className={styles.navBtn}
                        onClick={goToPrev}
                        disabled={currentSlide === 0}
                    >
                        ◀ 上一页
                    </button>

                    <div className={styles.slideIndicators}>
                        {slides.map((_, idx) => (
                            <button
                                key={idx}
                                className={`${styles.slideIndicator} ${idx === currentSlide ? styles.slideIndicatorActive : ''}`}
                                onClick={() => goToSlide(idx)}
                                title={`第 ${idx + 1} 页`}
                            />
                        ))}
                    </div>

                    <button
                        className={styles.navBtn}
                        onClick={goToNext}
                        disabled={currentSlide === slides.length - 1}
                    >
                        下一页 ▶
                    </button>
                </div>
            </div>
        );
    };

    // -- Main render ---------------------------------------------

    return (
        <div className={styles.presentationContainer}>
            {/* Messages area */}
            <div className={styles.messagesArea}>
                {messages.map(msg => (
                    <div
                        key={msg.id}
                        className={`${styles.messageBubble} ${msg.role === 'student' ? styles.messageStudent :
                                msg.role === 'coach' ? styles.messageCoach :
                                    styles.messageSystem
                            }`}
                    >
                        {msg.role !== 'system' && (
                            <div className={styles.messageHeader}>
                                <span className={`${styles.roleIcon} ${msg.role === 'student' ? styles.roleStudent : styles.roleCoach
                                    }`}>
                                    {msg.role === 'student' ? 'S' : 'AI'}
                                </span>
                                <span className={styles.roleLabel}>
                                    {msg.role === 'student' ? '我' : 'AI 导师'}
                                </span>
                            </div>
                        )}
                        <div className={styles.messageContent}>
                            {msg.role === 'coach' ? (
                                <MarkdownRenderer content={msg.content} />
                            ) : (
                                msg.content
                            )}
                        </div>
                    </div>
                ))}

                {/* Streaming content */}
                {streamingContent && (
                    <div className={`${styles.messageBubble} ${styles.messageCoach}`}>
                        <div className={styles.messageHeader}>
                            <span className={`${styles.roleIcon} ${styles.roleCoach}`}>AI</span>
                            <span className={styles.roleLabel}>AI 导师</span>
                        </div>
                        <div className={styles.messageContent}>
                            <MarkdownRenderer content={streamingContent} isStreaming />
                        </div>
                    </div>
                )}

                {renderThinking()}

                {/* Slide viewer */}
                {phase === 'viewing' && renderSlideViewer()}

                <div ref={messagesEndRef} />
            </div>

            {/* Input area */}
            <div className={styles.inputArea}>
                <textarea
                    ref={inputRef}
                    className={styles.chatInput}
                    value={input}
                    onChange={handleInputChange}
                    onKeyDown={handleKeyDown}
                    placeholder={
                        sending
                            ? 'AI 正在处理...'
                            : phase === 'generating'
                                ? '等待演示文稿生成...'
                                : '输入修改建议或其他问题... (Enter 发送)'
                    }
                    disabled={sending}
                    rows={1}
                />
                <button
                    className={styles.sendBtn}
                    onClick={handleSend}
                    disabled={!input.trim() || sending}
                >
                    发送
                </button>
            </div>
        </div>
    );
}
