'use client';

/**
 * Presentation Generator Skill Renderer.
 *
 * Slideshow UI that renders Markdown slides generated by the AI coach.
 * Parses <slides>...</slides> from coach responses and renders them
 * as an interactive slide deck with navigation controls.
 *
 * Phases: generating → viewing
 * Supports <slides>Markdown</slides> parsing from coach responses.
 */

import { useState, useRef, useCallback, useEffect, useMemo } from 'react';
import dynamic from 'next/dynamic';
import ChatInputArea from '@/components/ChatInputArea';
import type { SkillRendererProps } from '@/lib/plugin/types';
import styles from './PresentationRenderer.module.css';
import RevealDeck from '@/components/RevealDeck';
import { useTelemetry } from '@/lib/useTelemetry';
import TextSelectionTooltip from '@/components/TextSelectionTooltip';

const MarkdownRenderer = dynamic(() => import('@/components/MarkdownRenderer'));

// -- Types -------------------------------------------------------

interface ChatMessage {
    id: string;
    role: 'student' | 'coach' | 'system';
    content: string;
    timestamp: number;
}

type PresentationPhase = 'generating' | 'viewing' | 'idle';

// -- Slides Parser -----------------------------------------------

/**
 * Extracts markdown slides content from the <slides> tag.
 *
 * @param content - Raw coach response string
 * @returns Array of slide markdown strings, or null if no slides found
 */
function parseSlidesFromContent(content: string): string | null {
    const match = content.match(/<slides>([\s\S]*?)<\/slides>/);
    if (!match) return null;
    return match[1].trim();
}

/**
 * Strips the <slides> tag from a message, returning any surrounding text.
 *
 * @param content - Raw coach response string
 * @returns The content with the <slides> block removed
 */
function stripSlidesTag(content: string): string {
    return content.replace(/<slides>[\s\S]*?<\/slides>/, '').trim();
}



// -- Component ---------------------------------------------------

export default function PresentationRenderer({
    agentChannel,
    onInteractionEvent,
    initialMessages = [],
    studentContext,
    knowledgePoint,
}: SkillRendererProps) {
    const [messages, setMessages] = useState<ChatMessage[]>([]);
    const [input, setInput] = useState('');
    const [sending, setSending] = useState(false);
    const [thinkingStatus, setThinkingStatus] = useState<string | null>(null);
    const streamingContentRef = useRef('');
    const [streamingContent, setStreamingContent] = useState('');

    const { trackEvent } = useTelemetry(studentContext?.sessionId || 0, studentContext?.courseId || 0);

    const handleSlideChange = useCallback((indexh: number, indexv: number) => {
        trackEvent({
            event_type: 'custom',
            skill_id: 'presentation_generator',
            kp_id: knowledgePoint?.id,
            trigger_reason: 'slide_changed',
            metadata: {
                slide_h: indexh,
                slide_v: indexv,
                timestamp: Date.now()
            }
        });
    }, [trackEvent, knowledgePoint]);

    // Presentation-specific state
    const [phase, setPhase] = useState<PresentationPhase>('generating');
    const [slidesMarkdown, setSlidesMarkdown] = useState<string | null>(null);
    const [isFullscreen, setIsFullscreen] = useState(false);

    const messagesEndRef = useRef<HTMLDivElement>(null);
    const slideContainerRef = useRef<HTMLDivElement>(null);
    const hasTriggeredRef = useRef(false);

    // -- Load initial messages -----------------------------------

    useEffect(() => {
        if (!initialMessages || initialMessages.length === 0) return;
        
        const parsedMessages: ChatMessage[] = [];
        let foundSlides: string | null = null;
        
        for (const msg of initialMessages) {
            if (msg.role === 'coach' && msg.content) {
                const s = parseSlidesFromContent(msg.content);
                if (s) {
                    foundSlides = s;
                    const intro = stripSlidesTag(msg.content);
                    if (intro) {
                        parsedMessages.push({
                            id: msg.id || `coach-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
                            role: 'coach',
                            content: intro,
                            timestamp: msg.timestamp || Date.now(),
                        });
                    }
                } else {
                    parsedMessages.push({
                        id: msg.id || `msg-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
                        role: msg.role as 'student' | 'coach' | 'system',
                        content: msg.content,
                        timestamp: msg.timestamp || Date.now(),
                    });
                }
            } else {
                parsedMessages.push({
                    id: msg.id || `msg-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
                    role: msg.role as 'student' | 'coach' | 'system',
                    content: msg.content,
                    timestamp: msg.timestamp || Date.now(),
                });
            }
        }
        
        setTimeout(() => {
            setMessages(parsedMessages);
            if (foundSlides) {
                setSlidesMarkdown(foundSlides);
                setPhase('idle');
                hasTriggeredRef.current = true;
            }
        }, 0);
    }, [initialMessages]);

    // -- Auto-generate if no initial messages --------------------

    useEffect(() => {
        if (
            !hasTriggeredRef.current &&
            initialMessages.length === 0 &&
            messages.length === 0 &&
            !sending &&
            !streamingContent
        ) {
            hasTriggeredRef.current = true;
            setTimeout(() => {
                setSending(true);
                setPhase('generating');
            }, 0);
            
            // Auto-trigger the backend to start generating the presentation
            agentChannel.send(JSON.stringify({
                event: 'user_message',
                payload: { text: '你好，请根据当前知识点生成一份详细的演示文稿。' },
                timestamp: Math.floor(Date.now() / 1000),
            }));
        }
    }, [initialMessages.length, messages.length, sending, streamingContent, agentChannel]);

    // -- Scroll to bottom ----------------------------------------

    const scrollToBottom = useCallback(() => {
        messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    }, []);

    useEffect(() => {
        scrollToBottom();
    }, [messages, streamingContent, thinkingStatus, scrollToBottom]);

    // -- Keyboard navigation ------------------------------------

    useEffect(() => {
        if (phase !== 'viewing') return;

        const handleKeyDown = (e: KeyboardEvent) => {
            if (e.key === 'Escape' && isFullscreen) {
                setIsFullscreen(false);
            } else if (e.key === 'f' || e.key === 'F') {
                setIsFullscreen(prev => !prev);
            }
        };

        window.addEventListener('keydown', handleKeyDown);
        return () => window.removeEventListener('keydown', handleKeyDown);
    }, [phase, isFullscreen]);

    // -- WebSocket message handling ------------------------------

    useEffect(() => {
        const unsubscribeMessage = agentChannel.onMessage((data: string) => {
            try {
                const event = JSON.parse(data);
                switch (event.event) {
                    case 'agent_thinking': {
                        setThinkingStatus(event.payload?.status || '正在生成演示文稿...');
                        break;
                    }
                    case 'token_delta': {
                        setThinkingStatus(null);
                        const newText = event.payload?.text || '';
                        streamingContentRef.current += newText;
                        setStreamingContent(streamingContentRef.current);
                        break;
                    }
                    case 'turn_complete': {
                        setThinkingStatus(null);
                        setSending(false);
                        const prev = streamingContentRef.current;
                        if (prev) {
                            const parsed = parseSlidesFromContent(prev);
                            if (parsed) {
                                setSlidesMarkdown(parsed);
                                setPhase('idle');

                                const intro = stripSlidesTag(prev);
                                if (intro) {
                                    setMessages(msgs => [...msgs, {
                                        id: `coach-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
                                        role: 'coach',
                                        content: intro,
                                        timestamp: Date.now(),
                                    }]);
                                }

                                onInteractionEvent({
                                    type: 'presentation_generated',
                                    payload: {
                                        skillId: 'presentation_generator',
                                    },
                                    timestamp: Date.now(),
                                });
                            } else {
                                setMessages(msgs => [...msgs, {
                                    id: `coach-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
                                    role: 'coach',
                                    content: prev,
                                    timestamp: Date.now(),
                                }]);
                            }
                        }
                        streamingContentRef.current = '';
                        setStreamingContent('');
                        break;
                    }
                    case 'ui_scaffold_change': {
                        const payload = event.payload as {
                            data: { new_level: string; mastery: number; direction: string };
                        };
                        const direction = payload.data.direction === 'fade' ? '降低' : '增强';
                        const labels = { high: '高支架', medium: '中支架', low: '低支架' };
                        const label = labels[payload.data.new_level as keyof typeof labels] || payload.data.new_level;
                        setMessages(prev => [...prev, {
                            id: `sys-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
                            role: 'system',
                            content: `支架已${direction}至 ${label} (掌握度: ${(payload.data.mastery * 100).toFixed(0)}%)`,
                            timestamp: Date.now(),
                        }]);
                        break;
                    }
                    case 'error': {
                        setThinkingStatus(null);
                        setSending(false);
                        setMessages(prev => [...prev, {
                            id: `err-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
                            role: 'system',
                            content: event.payload?.message || '发生错误',
                            timestamp: Date.now(),
                        }]);
                        break;
                    }
                }
            } catch {
                // Ignore parse errors
            }
        });

        const unsubscribeClose = agentChannel.onClose(() => {
            setMessages(prev => [...prev, {
                id: `sys-close-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
                role: 'system',
                content: '连接已断开',
                timestamp: Date.now(),
            }]);
        });
        return () => {
            unsubscribeMessage();
            unsubscribeClose();
        };
    }, [agentChannel, onInteractionEvent]);

    // -- Request regeneration ------------------------------------

    const handleRegenerate = useCallback(() => {
        setPhase('generating');
        setSlidesMarkdown(null);

        agentChannel.send(JSON.stringify({
            event: 'user_message',
            payload: { text: '请重新生成演示文稿' },
            timestamp: Math.floor(Date.now() / 1000),
        }));

        setSending(true);
        streamingContentRef.current = '';
        setStreamingContent('');
    }, [agentChannel]);

    // -- Free-form message send ---------------------------------

    const handleSend = useCallback(() => {
        const text = input.trim();
        if (!text || sending) return;

        setMessages(prev => [...prev, {
            id: `student-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
            role: 'student',
            content: text,
            timestamp: Date.now(),
        }]);

        agentChannel.send(JSON.stringify({
            event: 'user_message',
            payload: { text },
            timestamp: Math.floor(Date.now() / 1000),
        }));

        setInput('');
        setSending(true);
        streamingContentRef.current = '';
        setStreamingContent('');
    }, [input, sending, agentChannel]);

    

    // -- Render Slide Viewer or Content wrapper -----------------

    const handleAskAI = useCallback((selectedText: string) => {
        setInput(prev => {
            const prefix = prev.length > 0 && !prev.endsWith('\n') ? prev + '\n' : prev;
            return prefix + `> ${selectedText}\n\n请解释一下这段话：`;
        });
        // Optionally focus the input if possible, but state update might be enough
    }, []);

    const renderThinking = () => {
        if (!thinkingStatus) return null;
        return (
            <div className={styles.thinkingIndicator}>
                <div className={styles.thinkingDots}>
                    <div className={styles.thinkingDot} />
                    <div className={styles.thinkingDot} />
                    <div className={styles.thinkingDot} />
                </div>
                <span>{thinkingStatus}</span>
            </div>
        );
    };

    // -- Render slide viewer -------------------------------------

    const renderSlideViewer = () => {
        if (!slidesMarkdown) return null;

        return (
            <div
                ref={slideContainerRef}
                className={`${styles.slideViewer} ${isFullscreen ? styles.slideViewerFullscreen : ''}`}
                style={{ padding: 0, height: '600px', display: 'flex', flexDirection: 'column' }}
            >
                {/* Toolbar */}
                <div className={styles.slideToolbar} style={{ zIndex: 10 }}>
                    <div className={styles.slideCounter}>
                        <span className={styles.slideCounterCurrent}>演示文稿</span>
                    </div>
                    <div className={styles.toolbarActions}>
                        <button
                            className={styles.toolbarBtn}
                            onClick={() => setIsFullscreen(prev => !prev)}
                            title="全屏模式 (F)"
                        >
                            {isFullscreen ? '⬜' : '⛶'}
                        </button>
                        <button
                            className={styles.toolbarBtn}
                            onClick={() => setPhase('idle')}
                            title="收起演示文稿"
                        >
                            收起
                        </button>
                        <button
                            className={styles.toolbarBtn}
                            onClick={handleRegenerate}
                            disabled={sending}
                            title="重新生成"
                        >
                            🔄
                        </button>
                    </div>
                </div>

                {/* RevealDeck */}
                <div style={{ flex: 1, position: 'relative' }}>
                    <RevealDeck key={slidesMarkdown} markdown={slidesMarkdown} onSlideChange={handleSlideChange} />
                </div>
            </div>
        );
    };

    // -- Main render ---------------------------------------------

    return (
        <div className={styles.presentationContainer}>
            <TextSelectionTooltip onAsk={handleAskAI} />
            {/* Messages area */}
            <div className={styles.messagesArea}>
                {messages.map(msg => (
                    <div
                        key={msg.id}
                        className={`${styles.messageBubble} ${msg.role === 'student' ? styles.messageStudent :
                                msg.role === 'coach' ? styles.messageCoach :
                                    styles.messageSystem
                            }`}
                    >
                        {msg.role !== 'system' && (
                            <div className={styles.messageHeader}>
                                <span className={`${styles.roleIcon} ${msg.role === 'student' ? styles.roleStudent : styles.roleCoach
                                    }`}>
                                    {msg.role === 'student' ? 'S' : 'AI'}
                                </span>
                                <span className={styles.roleLabel}>
                                    {msg.role === 'student' ? '我' : 'AI 导师'}
                                </span>
                            </div>
                        )}
                        <div className={styles.messageContent}>
                            {msg.role === 'coach' ? (
                                <MarkdownRenderer content={msg.content} />
                            ) : (
                                msg.content
                            )}
                        </div>
                    </div>
                ))}

                {/* Streaming content */}
                {streamingContent && (
                    <div className={`${styles.messageBubble} ${styles.messageCoach}`}>
                        <div className={styles.messageHeader}>
                            <span className={`${styles.roleIcon} ${styles.roleCoach}`}>AI</span>
                            <span className={styles.roleLabel}>AI 导师</span>
                        </div>
                        <div className={styles.messageContent}>
                            <MarkdownRenderer content={streamingContent} isStreaming />
                        </div>
                    </div>
                )}

                {renderThinking()}

                {/* Show Presentation Button */}
                {slidesMarkdown && phase === 'idle' && (
                    <div style={{
                        margin: '24px 0',
                        padding: '24px',
                        background: 'var(--bg-surface)',
                        border: '1px solid var(--border)',
                        borderRadius: '12px',
                        textAlign: 'center',
                        boxShadow: '0 4px 12px rgba(0,0,0,0.05)'
                    }}>
                        <div style={{ fontSize: '32px', marginBottom: '12px' }}>🎉</div>
                        <h3 style={{ margin: '0 0 8px 0', color: 'var(--text-primary)' }}>演示文稿已生成</h3>
                        <p style={{ margin: '0 0 20px 0', color: 'var(--text-secondary)', fontSize: '14px' }}>
                            已为你准备好互动演示材料
                        </p>
                        <button 
                            style={{ 
                                padding: '10px 28px', 
                                fontSize: '16px', 
                                fontWeight: 500,
                                borderRadius: '8px', 
                                cursor: 'pointer', 
                                background: 'var(--primary, #4a7dff)', 
                                color: '#fff', 
                                border: 'none',
                                transition: 'all 0.2s ease',
                                boxShadow: '0 2px 6px rgba(74, 125, 255, 0.3)'
                            }}
                            onClick={() => setPhase('viewing')}
                            onMouseOver={e => e.currentTarget.style.transform = 'translateY(-1px)'}
                            onMouseOut={e => e.currentTarget.style.transform = 'translateY(0)'}
                        >
                            📊 立即查看演示文稿
                        </button>
                    </div>
                )}

                {/* Slide viewer */}
                {phase === 'viewing' && renderSlideViewer()}

                <div ref={messagesEndRef} />
            </div>

            {/* Input */}
            <ChatInputArea
                input={input}
                setInput={setInput}
                sending={sending}
                onSend={() => handleSend()}
                placeholder={sending ? '处理中...' : '输入消息...'}
            />
        </div>
    );
}